branch-defaults:
  default:
    environment: people-api-dev
global:
  application_name: people_api
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
